import arcade
from styles.preferences import *

SCREEN_TITLE = "Alchemy"

SCREEN_WIDTH, SCREEN_HEIGHT = arcade.get_display_size()
SCREEN_MIDDLE_WIDTH = SCREEN_WIDTH // 2
SCREEN_MIDDLE_HEIGHT = SCREEN_HEIGHT // 2

BUTTON_IMAGE_PATH = "art/functional/"
LOG = "data/log.txt"

SETTING_BUTTON_X = 40
SETTING_BUTTON_Y = 40
SETTING_BUTTON_RADIUS = 25

RIGHT_PANEL_SCALE = 7
TRANSPARENT_BLACK = (0, 0, 0, 150)

PADDING_HEIGHT = 50

BACK_BUTTON_X = SCREEN_WIDTH - 40
BACK_BUTTON_Y = 40
BACK_BUTTON_RADIUS = 25
