from styles.constants import (
    SCREEN_WIDTH,
    SCREEN_HEIGHT,
    RIGHT_PANEL_SCALE,
)

from styles.assets import RECYCLE_ICON, ALL_ELEMENTS_ICON

RIGHT_PANEL_WIDTH = SCREEN_WIDTH // RIGHT_PANEL_SCALE
RIGHT_PANEL_LEFT_BORDER = SCREEN_WIDTH - RIGHT_PANEL_WIDTH
RIGHT_PANEL_MIDDLE_WIDTH = RIGHT_PANEL_LEFT_BORDER + RIGHT_PANEL_WIDTH / 2

RIGHT_PANEL_HEIGHT = SCREEN_HEIGHT * 2
RIGHT_PANEL_MIDDLE_HEIGHT = SCREEN_HEIGHT
RIGHT_PANEL_LEFT_EDGE = RIGHT_PANEL_LEFT_BORDER

PADDING_WIDTH = RIGHT_PANEL_LEFT_BORDER + 50

BUTTON_LEFT_WALL = RIGHT_PANEL_LEFT_BORDER
BUTTON_RIGHT_WALL = RIGHT_PANEL_LEFT_BORDER + 300

CLEAR_BUTTON_BOTTOM_WALL = RECYCLE_ICON.height - 40
CLEAR_BUTTON_TOP_WALL = RECYCLE_ICON.height + 40

ELEMENT_BUTTON_BOTTOM_WALL = (ALL_ELEMENTS_ICON.height - 40) + 82
ELEMENT_BUTTON_TOP_WALL = (ALL_ELEMENTS_ICON.height + 40) + 82
